[package]
name = "mangonel-libxdp-sys"
version = "0.1.0"
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[build-dependencies]
mangonel-util = { workspace = true }

bindgen = "0.71"
