[package]
name = "mangonel-nic"
version = "0.1.0"
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
default-net = "0.22"
thiserror = { workspace = true }
